spring:
  config:
    import:
      - classpath:application-secret.yml
      - classpath:application-database.yml
      - classpath:application-s3.yml
      - classpath:application-webhook-discord.yml
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
geoip2:
  database:
    path: GeoLite2-Country.mmdb

springdoc:
  swagger-ui:
    path: /swagger




