spring:
  config:
    import:
      - classpath:application-secret.yml
      - classpath:application-database-local.yml
      - classpath:application-database-prod.yml
      - classpath:application-s3.yml
      - classpath:application-webhook-discord.yml
      - classpath:application-firebase.yml

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  web:
    resources:
      add-mappings: false # 정적 리소스 제공 비활성화
geoip2:
  database:
    path: GeoLite2-Country.mmdb

springdoc:
  swagger-ui:
    path: /swagger




